# 网站标题
title: sora's blog
# 作者名称
author: sora
# 网站关键字
keyword: blog,hku
#false是否开启文章背景图显示(随机图片)
is_article_img: true
# 网站描述
web_description: blog
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: block-card
# 导航名称
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# logo
logo: /image/hku2.png
# 网页标签上那个小图标 一定要用本地存储
# icon: /image/favicon.ico
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "Sapientia et Virtus",
      icon: "/image/protrait_round.png"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: " year years, number posts.",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
    }
    tags: {
      message: "Labelling is a good habit",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
    }
    links: {
      message: "External Links",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
    }
    categories: {
      message: "See it, xxx, Sorted",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
    }

# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fadsfs  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论 
gitalk:
  clientID: Ov23lifWFXn6goW60chc # （需要替换）GitHub Application Client ID.
  clientSecret: 15f7e277e9ac9b063bd533995cbd28349548666b #（需要替换）GitHub Application Client Secret.
  repo: blog_comments #（需要替换）GitHub repository.
  owner: wannacry601 #（需要替换）GitHub repository 所有者，可以是个人或者组织。
  admin: ['wannacry601'] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    name: 'bilibili',
    # iconLink: 'https://upload.wikimedia.org/wikipedia/en/b/b7/Bilibili_logo.svg',
    iconLink: 'https://img.icons8.com/?size=100&id=5E24fZ9ORelo&format=png&color=000000',
    toUrl: 'https://space.bilibili.com/104509641'
  }
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/wannacry601'
  }
  - {
    #描述名称
    name: 'RSS',
    #图标    
    iconLink: 'https://cdn4.iconfinder.com/data/icons/iconsimple-logotypes/512/rss-512.png',
    #跳转链接    
    toUrl: 'https://blog.s0ra.cc/atom.xml'
  }
# 友情链接
linksList:
  - {
    title: 'Quiet',
    intro: 'Source of this theme',
    link: 'https://github.com/79E/hexo-theme-quiet',
    image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgIMG_7327.jpeg'
  }
  - {
    title: 'The University of Hong Kong',
    intro: 'HKU official website',
    link: 'https://hku.hk/',
    image: '../image/hku.png'
  }
  - {
    title: 'HKU EEE',
    intro: "EEE Department",
    link: 'https://www.eee.hku.hk/',
    image: '../image/hku.png'
  }
  # - {
  #   title: 'Museum 16',
  #   intro: '博物馆小队！',
  #   link: 'https://blog.museum16.com/',
  #   image: '../image/pattern.png'
  # }
  - {
    title: "thisisxxz",
    intro: 'xxz blog',
    link: 'https://thisisxxz.com/',
    image: 'https://thisisxxz.com/uploads/avatar-sumire.jpg'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: 'image/covers/default.png'
rss: /atom.xml